spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/ZSuiteTech/fintech_devcon_charts
    targetRevision: HEAD

deployWatchman: true
deployWatchmanIngress: false
